// Code generated by help.awk. DO NOT EDIT.
// GENERATED FILE DO NOT EDIT

package parser

var helpMessages = map[string]HelpMessageBody{
	//line sql.y: 923
	`ALTER`: {
		//line sql.y: 924
		Category: hGroup,
		//line sql.y: 925
		Text: `ALTER TABLE, ALTER INDEX, ALTER VIEW, ALTER DATABASE
`,
	},
	//line sql.y: 933
	`ALTER TABLE`: {
		ShortDescription: `change the definition of a table`,
		//line sql.y: 934
		Category: hDDL,
		//line sql.y: 935
		Text: `
ALTER TABLE [IF EXISTS] <tablename> <command> [, ...]

Commands:
  ALTER TABLE ... ADD [COLUMN] [IF NOT EXISTS] <colname> <type> [<qualifiers...>]
  ALTER TABLE ... ADD <constraint>
  ALTER TABLE ... DROP [COLUMN] [IF EXISTS] <colname> [RESTRICT | CASCADE]
  ALTER TABLE ... DROP CONSTRAINT [IF EXISTS] <constraintname> [RESTRICT | CASCADE]
  ALTER TABLE ... ALTER [COLUMN] <colname> {SET DEFAULT <expr> | DROP DEFAULT}
  ALTER TABLE ... ALTER [COLUMN] <colname> DROP NOT NULL
  ALTER TABLE ... RENAME TO <newname>
  ALTER TABLE ... RENAME [COLUMN] <colname> TO <newname>
  ALTER TABLE ... VALIDATE CONSTRAINT <constraintname>
  ALTER TABLE ... SPLIT AT <selectclause>
  ALTER TABLE ... SCATTER [ FROM ( <exprs...> ) TO ( <exprs...> ) ]

Column qualifiers:
  [CONSTRAINT <constraintname>] {NULL | NOT NULL | UNIQUE | PRIMARY KEY | CHECK (<expr>) | DEFAULT <expr>}
  FAMILY <familyname>, CREATE [IF NOT EXISTS] FAMILY [<familyname>]
  REFERENCES <tablename> [( <colnames...> )]
  COLLATE <collationname>

`,
		//line sql.y: 957
		SeeAlso: `https://www.cockroachlabs.com/docs/alter-table.html
`,
	},
	//line sql.y: 968
	`ALTER VIEW`: {
		ShortDescription: `change the definition of a view`,
		//line sql.y: 969
		Category: hDDL,
		//line sql.y: 970
		Text: `
ALTER VIEW [IF EXISTS] <name> RENAME TO <newname>
`,
		//line sql.y: 972
		SeeAlso: `https://www.cockroachlabs.com/docs/alter-view.html
`,
	},
	//line sql.y: 979
	`ALTER DATABASE`: {
		ShortDescription: `change the definition of a database`,
		//line sql.y: 980
		Category: hDDL,
		//line sql.y: 981
		Text: `
ALTER DATABASE <name> RENAME TO <newname>
`,
		//line sql.y: 983
		SeeAlso: `https://www.cockroachlabs.com/docs/alter-database.html
`,
	},
	//line sql.y: 990
	`ALTER INDEX`: {
		ShortDescription: `change the definition of an index`,
		//line sql.y: 991
		Category: hDDL,
		//line sql.y: 992
		Text: `
ALTER INDEX [IF EXISTS] <idxname> <command>

Commands:
  ALTER INDEX ... RENAME TO <newname>
  ALTER INDEX ... SPLIT AT <selectclause>
  ALTER INDEX ... SCATTER [ FROM ( <exprs...> ) TO ( <exprs...> ) ]

`,
		//line sql.y: 1000
		SeeAlso: `https://www.cockroachlabs.com/docs/alter-index.html
`,
	},
	//line sql.y: 1210
	`BACKUP`: {
		ShortDescription: `back up data to external storage`,
		//line sql.y: 1211
		Category: hCCL,
		//line sql.y: 1212
		Text: `
BACKUP <targets...> TO <location...>
       [ AS OF SYSTEM TIME <expr> ]
       [ INCREMENTAL FROM <location...> ]
       [ WITH <option> [= <value>] [, ...] ]

Targets:
   TABLE <pattern> [, ...]
   DATABASE <databasename> [, ...]

Location:
   "[scheme]://[host]/[path to backup]?[parameters]"

Options:
   INTO_DB
   SKIP_MISSING_FOREIGN_KEYS

`,
		//line sql.y: 1229
		SeeAlso: `RESTORE, https://www.cockroachlabs.com/docs/backup.html
`,
	},
	//line sql.y: 1237
	`RESTORE`: {
		ShortDescription: `restore data from external storage`,
		//line sql.y: 1238
		Category: hCCL,
		//line sql.y: 1239
		Text: `
RESTORE <targets...> FROM <location...>
        [ AS OF SYSTEM TIME <expr> ]
        [ WITH <option> [= <value>] [, ...] ]

Targets:
   TABLE <pattern> [, ...]
   DATABASE <databasename> [, ...]

Locations:
   "[scheme]://[host]/[path to backup]?[parameters]"

Options:
   INTO_DB
   SKIP_MISSING_FOREIGN_KEYS

`,
		//line sql.y: 1255
		SeeAlso: `BACKUP, https://www.cockroachlabs.com/docs/restore.html
`,
	},
	//line sql.y: 1269
	`IMPORT`: {
		ShortDescription: `load data from file in a distributed manner`,
		//line sql.y: 1270
		Category: hCCL,
		//line sql.y: 1271
		Text: `
IMPORT TABLE <tablename>
       { ( <elements> ) | CREATE USING <schemafile> }
       <format>
       DATA ( <datafile> [, ...] )
       [ WITH <option> [= <value>] [, ...] ]

Formats:
   CSV

Options:
   distributed = '...'
   sstsize = '...'
   temp = '...'
   comma = '...'          [CSV-specific]
   comment = '...'        [CSV-specific]
   nullif = '...'         [CSV-specific]

`,
		//line sql.y: 1289
		SeeAlso: `CREATE TABLE
`,
	},
	//line sql.y: 1384
	`CANCEL`: {
		//line sql.y: 1385
		Category: hGroup,
		//line sql.y: 1386
		Text: `CANCEL JOB, CANCEL QUERY
`,
	},
	//line sql.y: 1392
	`CANCEL JOB`: {
		ShortDescription: `cancel a background job`,
		//line sql.y: 1393
		Category: hMisc,
		//line sql.y: 1394
		Text: `CANCEL JOB <jobid>
`,
		//line sql.y: 1395
		SeeAlso: `SHOW JOBS, PAUSE JOBS, RESUME JOB
`,
	},
	//line sql.y: 1403
	`CANCEL QUERY`: {
		ShortDescription: `cancel a running query`,
		//line sql.y: 1404
		Category: hMisc,
		//line sql.y: 1405
		Text: `CANCEL QUERY <queryid>
`,
		//line sql.y: 1406
		SeeAlso: `SHOW QUERIES
`,
	},
	//line sql.y: 1414
	`CREATE`: {
		//line sql.y: 1415
		Category: hGroup,
		//line sql.y: 1416
		Text: `
CREATE DATABASE, CREATE TABLE, CREATE INDEX, CREATE TABLE AS,
CREATE USER, CREATE VIEW
`,
	},
	//line sql.y: 1432
	`DELETE`: {
		ShortDescription: `delete rows from a table`,
		//line sql.y: 1433
		Category: hDML,
		//line sql.y: 1434
		Text: `DELETE FROM <tablename> [WHERE <expr>] [RETURNING <exprs...>]
`,
		//line sql.y: 1435
		SeeAlso: `https://www.cockroachlabs.com/docs/delete.html
`,
	},
	//line sql.y: 1443
	`DISCARD`: {
		ShortDescription: `reset the session to its initial state`,
		//line sql.y: 1444
		Category: hCfg,
		//line sql.y: 1445
		Text: `DISCARD ALL
`,
	},
	//line sql.y: 1457
	`DROP`: {
		//line sql.y: 1458
		Category: hGroup,
		//line sql.y: 1459
		Text: `DROP DATABASE, DROP INDEX, DROP TABLE, DROP VIEW, DROP USER
`,
	},
	//line sql.y: 1468
	`DROP VIEW`: {
		ShortDescription: `remove a view`,
		//line sql.y: 1469
		Category: hDDL,
		//line sql.y: 1470
		Text: `DROP VIEW [IF EXISTS] <tablename> [, ...] [CASCADE | RESTRICT]
`,
		//line sql.y: 1471
		SeeAlso: `https://www.cockroachlabs.com/docs/drop-index.html
`,
	},
	//line sql.y: 1483
	`DROP TABLE`: {
		ShortDescription: `remove a table`,
		//line sql.y: 1484
		Category: hDDL,
		//line sql.y: 1485
		Text: `DROP TABLE [IF EXISTS] <tablename> [, ...] [CASCADE | RESTRICT]
`,
		//line sql.y: 1486
		SeeAlso: `https://www.cockroachlabs.com/docs/drop-table.html
`,
	},
	//line sql.y: 1498
	`DROP INDEX`: {
		ShortDescription: `remove an index`,
		//line sql.y: 1499
		Category: hDDL,
		//line sql.y: 1500
		Text: `DROP INDEX [IF EXISTS] <idxname> [, ...] [CASCADE | RESTRICT]
`,
		//line sql.y: 1501
		SeeAlso: `https://www.cockroachlabs.com/docs/drop-index.html
`,
	},
	//line sql.y: 1521
	`DROP DATABASE`: {
		ShortDescription: `remove a database`,
		//line sql.y: 1522
		Category: hDDL,
		//line sql.y: 1523
		Text: `DROP DATABASE [IF EXISTS] <databasename>
`,
		//line sql.y: 1524
		SeeAlso: `https://www.cockroachlabs.com/docs/drop-database.html
`,
	},
	//line sql.y: 1536
	`DROP USER`: {
		ShortDescription: `remove a user`,
		//line sql.y: 1537
		Category: hPriv,
		//line sql.y: 1538
		Text: `DROP USER [IF EXISTS] <user> [, ...]
`,
		//line sql.y: 1539
		SeeAlso: `CREATE USER, SHOW USERS
`,
	},
	//line sql.y: 1581
	`EXPLAIN`: {
		ShortDescription: `show the logical plan of a query`,
		//line sql.y: 1582
		Category: hMisc,
		//line sql.y: 1583
		Text: `
EXPLAIN <statement>
EXPLAIN [( [PLAN ,] <planoptions...> )] <statement>

Explainable statements:
    SELECT, CREATE, DROP, ALTER, INSERT, UPSERT, UPDATE, DELETE,
    SHOW, HELP, EXPLAIN, EXECUTE

Plan options:
    TYPES, EXPRS, METADATA, QUALIFY, INDENT, VERBOSE, DIST_SQL

`,
		//line sql.y: 1594
		SeeAlso: `https://www.cockroachlabs.com/docs/explain.html
`,
	},
	//line sql.y: 1644
	`PREPARE`: {
		ShortDescription: `prepare a statement for later execution`,
		//line sql.y: 1645
		Category: hMisc,
		//line sql.y: 1646
		Text: `PREPARE <name> [ ( <types...> ) ] AS <query>
`,
		//line sql.y: 1647
		SeeAlso: `EXECUTE, DEALLOCATE, DISCARD
`,
	},
	//line sql.y: 1669
	`EXECUTE`: {
		ShortDescription: `execute a statement prepared previously`,
		//line sql.y: 1670
		Category: hMisc,
		//line sql.y: 1671
		Text: `EXECUTE <name> [ ( <exprs...> ) ]
`,
		//line sql.y: 1672
		SeeAlso: `PREPARE, DEALLOCATE, DISCARD
`,
	},
	//line sql.y: 1695
	`DEALLOCATE`: {
		ShortDescription: `remove a prepared statement`,
		//line sql.y: 1696
		Category: hMisc,
		//line sql.y: 1697
		Text: `DEALLOCATE [PREPARE] { <name> | ALL }
`,
		//line sql.y: 1698
		SeeAlso: `PREPARE, EXECUTE, DISCARD
`,
	},
	//line sql.y: 1718
	`GRANT`: {
		ShortDescription: `define access privileges`,
		//line sql.y: 1719
		Category: hPriv,
		//line sql.y: 1720
		Text: `
GRANT {ALL | <privileges...> } ON <targets...> TO <grantees...>

Privileges:
  CREATE, DROP, GRANT, SELECT, INSERT, DELETE, UPDATE

Targets:
  DATABASE <databasename> [, ...]
  [TABLE] [<databasename> .] { <tablename> | * } [, ...]

`,
		//line sql.y: 1730
		SeeAlso: `REVOKE, https://www.cockroachlabs.com/docs/grant.html
`,
	},
	//line sql.y: 1738
	`REVOKE`: {
		ShortDescription: `remove access privileges`,
		//line sql.y: 1739
		Category: hPriv,
		//line sql.y: 1740
		Text: `
REVOKE {ALL | <privileges...> } ON <targets...> FROM <grantees...>

Privileges:
  CREATE, DROP, GRANT, SELECT, INSERT, DELETE, UPDATE

Targets:
  DATABASE <databasename> [, <databasename>]...
  [TABLE] [<databasename> .] { <tablename> | * } [, ...]

`,
		//line sql.y: 1750
		SeeAlso: `GRANT, https://www.cockroachlabs.com/docs/revoke.html
`,
	},
	//line sql.y: 1833
	`RESET`: {
		ShortDescription: `reset a session variable to its default value`,
		//line sql.y: 1834
		Category: hCfg,
		//line sql.y: 1835
		Text: `RESET [SESSION] <var>
`,
		//line sql.y: 1836
		SeeAlso: `https://www.cockroachlabs.com/docs/set-vars.html
`,
	},
	//line sql.y: 1866
	`SET CLUSTER SETTING`: {
		ShortDescription: `change a cluster setting`,
		//line sql.y: 1867
		Category: hCfg,
		//line sql.y: 1868
		Text: `SET CLUSTER SETTING <var> { TO | = } <value>
`,
		//line sql.y: 1869
		SeeAlso: `SHOW CLUSTER SETTING, SET SESSION,
https://www.cockroachlabs.com/docs/cluster-settings.html
`,
	},
	//line sql.y: 1887
	`SET SESSION`: {
		ShortDescription: `change a session variable`,
		//line sql.y: 1888
		Category: hCfg,
		//line sql.y: 1889
		Text: `
SET [SESSION] <var> { TO | = } <values...>
SET [SESSION] TIME ZONE <tz>
SET [SESSION] CHARACTERISTICS AS TRANSACTION ISOLATION LEVEL { SNAPSHOT | SERIALIZABLE }

`,
		//line sql.y: 1894
		SeeAlso: `SHOW SESSION, RESET, DISCARD, SHOW, SET CLUSTER SETTING, SET TRANSACTION,
https://www.cockroachlabs.com/docs/set-vars.html
`,
	},
	//line sql.y: 1911
	`SET TRANSACTION`: {
		ShortDescription: `configure the transaction settings`,
		//line sql.y: 1912
		Category: hTxn,
		//line sql.y: 1913
		Text: `
SET [SESSION] TRANSACTION <txnparameters...>

Transaction parameters:
   ISOLATION LEVEL { SNAPSHOT | SERIALIZABLE }
   PRIORITY { LOW | NORMAL | HIGH }

`,
		//line sql.y: 1920
		SeeAlso: `SHOW TRANSACTION, SET SESSION,
https://www.cockroachlabs.com/docs/set-transaction.html
`,
	},
	//line sql.y: 2095
	`SHOW`: {
		//line sql.y: 2096
		Category: hGroup,
		//line sql.y: 2097
		Text: `
SHOW SESSION, SHOW CLUSTER SETTING, SHOW DATABASES, SHOW TABLES, SHOW COLUMNS, SHOW INDEXES,
SHOW CONSTRAINTS, SHOW CREATE TABLE, SHOW CREATE VIEW, SHOW USERS, SHOW TRANSACTION, SHOW BACKUP,
SHOW JOBS, SHOW QUERIES, SHOW SESSIONS, SHOW TRACE
`,
	},
	//line sql.y: 2122
	`SHOW SESSION`: {
		ShortDescription: `display session variables`,
		//line sql.y: 2123
		Category: hCfg,
		//line sql.y: 2124
		Text: `SHOW [SESSION] { <var> | ALL }
`,
		//line sql.y: 2125
		SeeAlso: `https://www.cockroachlabs.com/docs/show-vars.html
`,
	},
	//line sql.y: 2146
	`SHOW BACKUP`: {
		ShortDescription: `list backup contents`,
		//line sql.y: 2147
		Category: hCCL,
		//line sql.y: 2148
		Text: `SHOW BACKUP <location>
`,
		//line sql.y: 2149
		SeeAlso: `https://www.cockroachlabs.com/docs/show-backup.html
`,
	},
	//line sql.y: 2157
	`SHOW CLUSTER SETTING`: {
		ShortDescription: `display cluster settings`,
		//line sql.y: 2158
		Category: hCfg,
		//line sql.y: 2159
		Text: `
SHOW CLUSTER SETTING <var>
SHOW ALL CLUSTER SETTINGS
`,
		//line sql.y: 2162
		SeeAlso: `https://www.cockroachlabs.com/docs/cluster-settings.html
`,
	},
	//line sql.y: 2179
	`SHOW COLUMNS`: {
		ShortDescription: `list columns in relation`,
		//line sql.y: 2180
		Category: hDDL,
		//line sql.y: 2181
		Text: `SHOW COLUMNS FROM <tablename>
`,
		//line sql.y: 2182
		SeeAlso: `https://www.cockroachlabs.com/docs/show-columns.html
`,
	},
	//line sql.y: 2190
	`SHOW DATABASES`: {
		ShortDescription: `list databases`,
		//line sql.y: 2191
		Category: hDDL,
		//line sql.y: 2192
		Text: `SHOW DATABASES
`,
		//line sql.y: 2193
		SeeAlso: `https://www.cockroachlabs.com/docs/show-databases.html
`,
	},
	//line sql.y: 2201
	`SHOW GRANTS`: {
		ShortDescription: `list grants`,
		//line sql.y: 2202
		Category: hPriv,
		//line sql.y: 2203
		Text: `SHOW GRANTS [ON <targets...>] [FOR <users...>]
`,
		//line sql.y: 2204
		SeeAlso: `https://www.cockroachlabs.com/docs/show-grants.html
`,
	},
	//line sql.y: 2212
	`SHOW INDEXES`: {
		ShortDescription: `list indexes`,
		//line sql.y: 2213
		Category: hDDL,
		//line sql.y: 2214
		Text: `SHOW INDEXES FROM <tablename>
`,
		//line sql.y: 2215
		SeeAlso: `https://www.cockroachlabs.com/docs/show-indexes.html
`,
	},
	//line sql.y: 2233
	`SHOW CONSTRAINTS`: {
		ShortDescription: `list constraints`,
		//line sql.y: 2234
		Category: hDDL,
		//line sql.y: 2235
		Text: `SHOW CONSTRAINTS FROM <tablename>
`,
		//line sql.y: 2236
		SeeAlso: `https://www.cockroachlabs.com/docs/show-constraints.html
`,
	},
	//line sql.y: 2249
	`SHOW QUERIES`: {
		ShortDescription: `list running queries`,
		//line sql.y: 2250
		Category: hMisc,
		//line sql.y: 2251
		Text: `SHOW [CLUSTER | LOCAL] QUERIES
`,
		//line sql.y: 2252
		SeeAlso: `CANCEL QUERY
`,
	},
	//line sql.y: 2268
	`SHOW JOBS`: {
		ShortDescription: `list background jobs`,
		//line sql.y: 2269
		Category: hMisc,
		//line sql.y: 2270
		Text: `SHOW JOBS
`,
		//line sql.y: 2271
		SeeAlso: `CANCEL JOB, PAUSE JOB, RESUME JOB
`,
	},
	//line sql.y: 2279
	`SHOW TRACE`: {
		ShortDescription: `display an execution trace`,
		//line sql.y: 2280
		Category: hMisc,
		//line sql.y: 2281
		Text: `
SHOW [KV] TRACE FOR SESSION
SHOW [KV] TRACE FOR <statement>
`,
		//line sql.y: 2284
		SeeAlso: `EXPLAIN
`,
	},
	//line sql.y: 2305
	`SHOW SESSIONS`: {
		ShortDescription: `list open client sessions`,
		//line sql.y: 2306
		Category: hMisc,
		//line sql.y: 2307
		Text: `SHOW [CLUSTER | LOCAL] SESSIONS
`,
	},
	//line sql.y: 2323
	`SHOW TABLES`: {
		ShortDescription: `list tables`,
		//line sql.y: 2324
		Category: hDDL,
		//line sql.y: 2325
		Text: `SHOW TABLES [FROM <databasename>]
`,
		//line sql.y: 2326
		SeeAlso: `https://www.cockroachlabs.com/docs/show-tables.html
`,
	},
	//line sql.y: 2338
	`SHOW TRANSACTION`: {
		ShortDescription: `display current transaction properties`,
		//line sql.y: 2339
		Category: hCfg,
		//line sql.y: 2340
		Text: `SHOW TRANSACTION {ISOLATION LEVEL | PRIORITY | STATUS}
`,
		//line sql.y: 2341
		SeeAlso: `https://www.cockroachlabs.com/docs/show-transaction.html
`,
	},
	//line sql.y: 2360
	`SHOW CREATE TABLE`: {
		ShortDescription: `display the CREATE TABLE statement for a table`,
		//line sql.y: 2361
		Category: hDDL,
		//line sql.y: 2362
		Text: `SHOW CREATE TABLE <tablename>
`,
		//line sql.y: 2363
		SeeAlso: `https://www.cockroachlabs.com/docs/show-create-table.html
`,
	},
	//line sql.y: 2371
	`SHOW CREATE VIEW`: {
		ShortDescription: `display the CREATE VIEW statement for a view`,
		//line sql.y: 2372
		Category: hDDL,
		//line sql.y: 2373
		Text: `SHOW CREATE VIEW <viewname>
`,
		//line sql.y: 2374
		SeeAlso: `https://www.cockroachlabs.com/docs/show-create-view.html
`,
	},
	//line sql.y: 2382
	`SHOW USERS`: {
		ShortDescription: `list defined users`,
		//line sql.y: 2383
		Category: hPriv,
		//line sql.y: 2384
		Text: `SHOW USERS
`,
		//line sql.y: 2385
		SeeAlso: `CREATE USER, DROP USER, https://www.cockroachlabs.com/docs/show-users.html
`,
	},
	//line sql.y: 2437
	`PAUSE JOB`: {
		ShortDescription: `pause a background job`,
		//line sql.y: 2438
		Category: hMisc,
		//line sql.y: 2439
		Text: `PAUSE JOB <jobid>
`,
		//line sql.y: 2440
		SeeAlso: `SHOW JOBS, CANCEL JOB, RESUME JOB
`,
	},
	//line sql.y: 2448
	`CREATE TABLE`: {
		ShortDescription: `create a new table`,
		//line sql.y: 2449
		Category: hDDL,
		//line sql.y: 2450
		Text: `
CREATE TABLE [IF NOT EXISTS] <tablename> ( <elements...> ) [<interleave>]
CREATE TABLE [IF NOT EXISTS] <tablename> [( <colnames...> )] AS <source>

Table elements:
   <name> <type> [<qualifiers...>]
   [UNIQUE] INDEX [<name>] ( <colname> [ASC | DESC] [, ...] )
                           [STORING ( <colnames...> )] [<interleave>]
   FAMILY [<name>] ( <colnames...> )
   [CONSTRAINT <name>] <constraint>

Table constraints:
   PRIMARY KEY ( <colnames...> )
   FOREIGN KEY ( <colnames...> ) REFERENCES <tablename> [( <colnames...> )]
   UNIQUE ( <colnames... ) [STORING ( <colnames...> )] [<interleave>]
   CHECK ( <expr> )

Column qualifiers:
  [CONSTRAINT <constraintname>] {NULL | NOT NULL | UNIQUE | PRIMARY KEY | CHECK (<expr>) | DEFAULT <expr>}
  FAMILY <familyname>, CREATE [IF NOT EXISTS] FAMILY [<familyname>]
  REFERENCES <tablename> [( <colnames...> )]
  COLLATE <collationname>

Interleave clause:
   INTERLEAVE IN PARENT <tablename> ( <colnames...> ) [CASCADE | RESTRICT]

`,
		//line sql.y: 2476
		SeeAlso: `SHOW TABLES, CREATE VIEW, SHOW CREATE TABLE,
https://www.cockroachlabs.com/docs/create-table.html
https://www.cockroachlabs.com/docs/create-table-as.html
`,
	},
	//line sql.y: 2810
	`TRUNCATE`: {
		ShortDescription: `empty one or more tables`,
		//line sql.y: 2811
		Category: hDML,
		//line sql.y: 2812
		Text: `TRUNCATE [TABLE] <tablename> [, ...] [CASCADE | RESTRICT]
`,
		//line sql.y: 2813
		SeeAlso: `https://www.cockroachlabs.com/docs/truncate.html
`,
	},
	//line sql.y: 2821
	`CREATE USER`: {
		ShortDescription: `define a new user`,
		//line sql.y: 2822
		Category: hPriv,
		//line sql.y: 2823
		Text: `CREATE USER <name> [ [WITH] PASSWORD <passwd> ]
`,
		//line sql.y: 2824
		SeeAlso: `DROP USER, SHOW USERS, https://www.cockroachlabs.com/docs/create-user.html
`,
	},
	//line sql.y: 2842
	`CREATE VIEW`: {
		ShortDescription: `create a new view`,
		//line sql.y: 2843
		Category: hDDL,
		//line sql.y: 2844
		Text: `CREATE VIEW <viewname> [( <colnames...> )] AS <source>
`,
		//line sql.y: 2845
		SeeAlso: `CREATE TABLE, SHOW CREATE VIEW, https://www.cockroachlabs.com/docs/create-view.html
`,
	},
	//line sql.y: 2859
	`CREATE INDEX`: {
		ShortDescription: `create a new index`,
		//line sql.y: 2860
		Category: hDDL,
		//line sql.y: 2861
		Text: `
CREATE [UNIQUE] INDEX [IF NOT EXISTS] [<idxname>]
       ON <tablename> ( <colname> [ASC | DESC] [, ...] )
       [STORING ( <colnames...> )] [<interleave>]

Interleave clause:
   INTERLEAVE IN PARENT <tablename> ( <colnames...> ) [CASCADE | RESTRICT]

`,
		//line sql.y: 2869
		SeeAlso: `CREATE TABLE, SHOW INDEXES, SHOW CREATE INDEX,
https://www.cockroachlabs.com/docs/create-index.html
`,
	},
	//line sql.y: 3008
	`RELEASE`: {
		ShortDescription: `complete a retryable block`,
		//line sql.y: 3009
		Category: hTxn,
		//line sql.y: 3010
		Text: `RELEASE [SAVEPOINT] cockroach_restart
`,
		//line sql.y: 3011
		SeeAlso: `SAVEPOINT, https://www.cockroachlabs.com/docs/savepoint.html
`,
	},
	//line sql.y: 3019
	`RESUME JOB`: {
		ShortDescription: `resume a background job`,
		//line sql.y: 3020
		Category: hMisc,
		//line sql.y: 3021
		Text: `RESUME JOB <jobid>
`,
		//line sql.y: 3022
		SeeAlso: `SHOW JOBS, CANCEL JOB, PAUSE JOB
`,
	},
	//line sql.y: 3030
	`SAVEPOINT`: {
		ShortDescription: `start a retryable block`,
		//line sql.y: 3031
		Category: hTxn,
		//line sql.y: 3032
		Text: `SAVEPOINT cockroach_restart
`,
		//line sql.y: 3033
		SeeAlso: `RELEASE, https://www.cockroachlabs.com/docs/savepoint.html
`,
	},
	//line sql.y: 3047
	`BEGIN`: {
		ShortDescription: `start a transaction`,
		//line sql.y: 3048
		Category: hTxn,
		//line sql.y: 3049
		Text: `
BEGIN [TRANSACTION] [ <txnparameter> [[,] ...] ]
START TRANSACTION [ <txnparameter> [[,] ...] ]

Transaction parameters:
   ISOLATION LEVEL { SNAPSHOT | SERIALIZABLE }
   PRIORITY { LOW | NORMAL | HIGH }

`,
		//line sql.y: 3057
		SeeAlso: `COMMIT, ROLLBACK, https://www.cockroachlabs.com/docs/begin-transaction.html
`,
	},
	//line sql.y: 3070
	`COMMIT`: {
		ShortDescription: `commit the current transaction`,
		//line sql.y: 3071
		Category: hTxn,
		//line sql.y: 3072
		Text: `
COMMIT [TRANSACTION]
END [TRANSACTION]
`,
		//line sql.y: 3075
		SeeAlso: `BEGIN, ROLLBACK, https://www.cockroachlabs.com/docs/commit-transaction.html
`,
	},
	//line sql.y: 3088
	`ROLLBACK`: {
		ShortDescription: `abort the current transaction`,
		//line sql.y: 3089
		Category: hTxn,
		//line sql.y: 3090
		Text: `ROLLBACK [TRANSACTION] [TO [SAVEPOINT] cockroach_restart]
`,
		//line sql.y: 3091
		SeeAlso: `BEGIN, COMMIT, SAVEPOINT, https://www.cockroachlabs.com/docs/rollback-transaction.html
`,
	},
	//line sql.y: 3205
	`CREATE DATABASE`: {
		ShortDescription: `create a new database`,
		//line sql.y: 3206
		Category: hDDL,
		//line sql.y: 3207
		Text: `CREATE DATABASE [IF NOT EXISTS] <name>
`,
		//line sql.y: 3208
		SeeAlso: `https://www.cockroachlabs.com/docs/create-database.html
`,
	},
	//line sql.y: 3289
	`INSERT`: {
		ShortDescription: `create new rows in a table`,
		//line sql.y: 3290
		Category: hDML,
		//line sql.y: 3291
		Text: `
INSERT INTO <tablename> [[AS] <name>] [( <colnames...> )]
       <selectclause>
       [ON CONFLICT [( <colnames...> )] {DO UPDATE SET ... [WHERE <expr>] | DO NOTHING}]
       [RETURNING <exprs...>]
`,
		//line sql.y: 3296
		SeeAlso: `UPSERT, UPDATE, DELETE, https://www.cockroachlabs.com/docs/insert.html
`,
	},
	//line sql.y: 3313
	`UPSERT`: {
		ShortDescription: `create or replace rows in a table`,
		//line sql.y: 3314
		Category: hDML,
		//line sql.y: 3315
		Text: `
UPSERT INTO <tablename> [AS <name>] [( <colnames...> )]
       <selectclause>
       [RETURNING <exprs...>]
`,
		//line sql.y: 3319
		SeeAlso: `INSERT, UPDATE, DELETE, https://www.cockroachlabs.com/docs/upsert.html
`,
	},
	//line sql.y: 3395
	`UPDATE`: {
		ShortDescription: `update rows of a table`,
		//line sql.y: 3396
		Category: hDML,
		//line sql.y: 3397
		Text: `UPDATE <tablename> [[AS] <name>] SET ... [WHERE <expr>] [RETURNING <exprs...>]
`,
		//line sql.y: 3398
		SeeAlso: `INSERT, UPSERT, DELETE, https://www.cockroachlabs.com/docs/update.html
`,
	},
	//line sql.y: 3566
	`<SELECTCLAUSE>`: {
		ShortDescription: `access tabular data`,
		//line sql.y: 3567
		Category: hDML,
		//line sql.y: 3568
		Text: `
Select clause:
  TABLE <tablename>
  VALUES ( <exprs...> ) [ , ... ]
  SELECT ... [ { INTERSECT | UNION | EXCEPT } [ ALL | DISTINCT ] <selectclause> ]
`,
	},
	//line sql.y: 3579
	`SELECT`: {
		ShortDescription: `retrieve rows from a data source and compute a result`,
		//line sql.y: 3580
		Category: hDML,
		//line sql.y: 3581
		Text: `
SELECT [DISTINCT]
       { <expr> [[AS] <name>] | [ [<dbname>.] <tablename>. ] * } [, ...]
       [ FROM <source> ]
       [ WHERE <expr> ]
       [ GROUP BY <expr> [ , ... ] ]
       [ HAVING <expr> ]
       [ WINDOW <name> AS ( <definition> ) ]
       [ { UNION | INTERSECT | EXCEPT } [ ALL | DISTINCT ] <selectclause> ]
       [ ORDER BY <expr> [ ASC | DESC ] [, ...] ]
       [ LIMIT { <expr> | ALL } ]
       [ OFFSET <expr> [ ROW | ROWS ] ]
`,
		//line sql.y: 3593
		SeeAlso: `https://www.cockroachlabs.com/docs/select.html
`,
	},
	//line sql.y: 3653
	`TABLE`: {
		ShortDescription: `select an entire table`,
		//line sql.y: 3654
		Category: hDML,
		//line sql.y: 3655
		Text: `TABLE <tablename>
`,
		//line sql.y: 3656
		SeeAlso: `SELECT, VALUES, https://www.cockroachlabs.com/docs/table-expressions.html
`,
	},
	//line sql.y: 3895
	`VALUES`: {
		ShortDescription: `select a given set of values`,
		//line sql.y: 3896
		Category: hDML,
		//line sql.y: 3897
		Text: `VALUES ( <exprs...> ) [, ...]
`,
		//line sql.y: 3898
		SeeAlso: `SELECT, TABLE, https://www.cockroachlabs.com/docs/table-expressions.html
`,
	},
	//line sql.y: 4003
	`<SOURCE>`: {
		ShortDescription: `define a data source for SELECT`,
		//line sql.y: 4004
		Category: hDML,
		//line sql.y: 4005
		Text: `
Data sources:
  <tablename> [ @ { <idxname> | <indexhint> } ]
  <tablefunc> ( <exprs...> )
  ( { <selectclause> | <source> } )
  <source> [AS] <alias> [( <colnames...> )]
  <source> { [INNER] | { LEFT | RIGHT } [OUTER] } JOIN <source> ON <expr>
  <source> { [INNER] | { LEFT | RIGHT } [OUTER] } JOIN <source> USING ( <colnames...> )
  <source> NATURAL { [INNER] | { LEFT | RIGHT } [OUTER] } JOIN <source>
  <source> CROSS JOIN <source>
  <source> WITH ORDINALITY
  '[' EXPLAIN ... ']'
  '[' SHOW ... ']'

Index hints:
  '{' FORCE_INDEX = <idxname> [, ...] '}'
  '{' NO_INDEX_JOIN [, ...] '}'

`,
		//line sql.y: 4023
		SeeAlso: `https://www.cockroachlabs.com/docs/table-expressions.html
`,
	},
}
